# Generated by Django 2.1.5 on 2019-02-10 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='indicador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_prevista', models.IntegerField()),
                ('executado', models.IntegerField()),
                ('nao_executado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='metas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_meta', models.IntegerField()),
                ('meta_description', models.TextField()),
                ('indicador_A', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicador_A', to='metas.indicador')),
                ('indicador_B', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicador_B', to='metas.indicador')),
            ],
        ),
    ]
