# Generated by Django 2.1.5 on 2019-02-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='Descricao_da_meta',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
