# Generated by Django 2.1.5 on 2019-02-10 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0002_indicador_descricao_da_meta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicador',
            old_name='Descricao_da_meta',
            new_name='Descrição_da_meta',
        ),
    ]
